#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  - nuget restore
platform:
  - Any CPU
configuration: Release
build:
  parallel: true                  
  project: src\QuartzNET-DynamoDB.sln    

#---------------------------------#
#       test configuration        #
#---------------------------------#
test:
  assemblies: 
    - QuartzNET-DynamoDB.Tests.dll
  categories:
    only:
      - Unit