environment:
  AWS_ACCESS_KEY_ID: AKID
  AWS_SECRET_ACCESS_KEY: SECRET
  AWS_REGION: us-east-1

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  - nuget restore src\QuartzNET-DynamoDB.sln 
platform:
  - Any CPU
configuration: Release
build:
  parallel: true                  
  project: src\QuartzNET-DynamoDB.sln    

#---------------------------------#
#       test configuration        #
#---------------------------------#
before_test:
  - ps: mkdir c:/tmp
  - ps: (new-object net.webclient).DownloadFile('http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.zip', 'c:/tmp/dynamodb_local.zip')
  - ps: Expand-Archive c:/tmp/dynamodb_local.zip -DestinationPath c:/tmp
  - ps: $MyProcess = Start-Process javaw.exe -PassThru -ArgumentList '-Djava.library.path', 'c:/tmp/DynamoDBLocal_lib', '-jar', 'c:/tmp/DynamoDBLocal.jar', '-inMemory' 

test:
  assemblies: 
    - QuartzNET-DynamoDB.Tests.dll
  categories:
    only:
      - Unit
      - Integration